### ISSUE TITLE
ValidationError compound fields in metadatablock social_science

### ISSUE THREAD

**Issue by CB-HAL** [gdcc/easyDataverse#45]
social science compound fields (targetSampleSize: Actual, Formula; socialScienceNotes: Type, Subject, Text) can’t be loaded and processed. 
Pydantic ValidationError:
social_science_notes.socialScienceNotesType
  Input should be a valid string [type=string_type, input_value=DottedDict({'typeName': '...al_Scienes_Notes_test'}), input_type=DottedDict]

**Comment by CB-HAL** [comment]
It's a non public test instance v6.2. But the same error also on v6.6 https://demo.dataverse.org/dataset.xhtml?persistentId=doi:10.70122/FK2/EEAP40

**Comment by JR-1991** [comment]
@CB-HAL this has been fixed in the Custom Terms PR as well.

* #48

**Comment by ffritze** [comment]
Hi Jan, we are still experiencing an issue with the social science metadata block. We are using DV 6.6 and easyDataverse 0.4.3.

**Comment by CB-HAL** [comment]
The social science metadata block bug was fixed with easyDataverse 0.4.4.

**Comment by ffritze** [comment]
Thanks a lot. I wasn't aware of this new release.
